spring.application.name=lab9

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab9
spring.datasource.username=postgres
spring.datasource.password=P@ssword

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8081
